server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true
logging:  level:    test: debug
    root: info
    '[org.springframework.web]': info
    '[org.springframework.security]': info
    '[org.springframework.boot.autoconfigure]': info
   